use_frameworks!

target 'RFCircleView_Example' do
  pod 'RFCircleView', :path => '../'

  target 'RFCircleView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
